// app/layout.tsx
import "./globals.scss";
import type { Metadata } from "next";
import { headers } from "next/headers";

import { cookieToInitialState } from "wagmi";

import { config } from "./config";
import Web3ModalProvider from "./context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookies = headers().get("cookie");
  return (
    <html lang="en">
      <body>
        <Web3ModalProvider cookies={cookies}>{children}</Web3ModalProvider>
      </body>
    </html>
  );
}
