services:
  treasury:
    container_name: treasury
    image: ghcr.io/oasisprotocol/sapphire-localnet:latest
    platform: linux/x86_64
    entrypoint: ["/start.sh", "-test-mnemonic"]
    environment:
      - LOG__LEVEL=debug
      - OASIS_NODE_LOG_LEVEL=debug
    ports:
      - ${TOKEN_AUTHORITY_RPC_PORT:-8845}:8545
      - ${TOKEN_AUTHORITY_RPC_PORT:-8846}:8546
    networks:
      - unboundscience

networks:
  unboundscience:
    name: unboundscience